# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: socialsin.com
email: michael@socialsin.com
description: > # this means to ignore newlines until "baseurl:"
  To Do: Work more 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://socialsin.com" # the base hostname & protocol for your site
twitter_username: socialsin
github_username:  mschneider247

# Build settings
markdown: kramdown
